处理缺失数据

In [1]:
import pandas as pd
import numpy as np

In [2]:
float_data = pd.Series([1.2,-3.5,np.nan,0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [3]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])
string_data

0    aardvark
1         NaN
2         NaN
3     avocado
dtype: str

In [4]:
float_data = pd.Series([1,2,None],dtype="float64")
display(float_data)

0    1.0
1    2.0
2    NaN
dtype: float64

过滤缺失数据

In [5]:
data = pd.Series([1,np.nan,3.5,np.nan,7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [6]:
data.dropna()
# data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [7]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                    [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
2,NaN,NaN,NaN
3,NaN,6.5,3.0


In [8]:
data.dropna()

,0,1,2
0,1.0,6.5,3.0


In [9]:
display(data)
data.dropna(how="all")
# 只删除行为NA

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
2,NaN,NaN,NaN
3,NaN,6.5,3.0


,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
3,NaN,6.5,3.0


In [10]:
data[4] = np.nan

In [11]:
data.dropna(axis=1,how="all")
# how to drop

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
2,NaN,NaN,NaN
3,NaN,6.5,3.0


In [12]:
df = pd.DataFrame(np.random.standard_normal((7,3)))
display(df)

,0,1,2
0,1.243484,0.507744,0.835163
1,-0.076418,0.111700,-1.013368
2,0.262427,-0.016603,1.862489
3,-0.545994,-1.048251,0.482823
4,1.013460,0.023364,-2.136266
5,-0.685733,-0.862155,1.204126
6,-0.858191,-1.300200,0.210353


In [13]:
df.iloc[:4,1] = np.nan
df.iloc[:2,2] = np.nan
df
# 取值时：一般是先行后列
# 创建/理解表结构时：常常先列后行


,0,1,2
0,1.243484,NaN,NaN
1,-0.076418,NaN,NaN
2,0.262427,NaN,1.862489
3,-0.545994,NaN,0.482823
4,1.013460,0.023364,-2.136266
5,-0.685733,-0.862155,1.204126
6,-0.858191,-1.300200,0.210353


In [14]:
df.dropna(thresh=2)
# 指定保留缺失观测值的行

,0,1,2
2,0.262427,NaN,1.862489
3,-0.545994,NaN,0.482823
4,1.013460,0.023364,-2.136266
5,-0.685733,-0.862155,1.204126
6,-0.858191,-1.300200,0.210353


填充缺失数据

In [15]:
df

,0,1,2
0,1.243484,NaN,NaN
1,-0.076418,NaN,NaN
2,0.262427,NaN,1.862489
3,-0.545994,NaN,0.482823
4,1.013460,0.023364,-2.136266
5,-0.685733,-0.862155,1.204126
6,-0.858191,-1.300200,0.210353


In [16]:
df.fillna(0)

,0,1,2
0,1.243484,0.000000,0.000000
1,-0.076418,0.000000,0.000000
2,0.262427,0.000000,1.862489
3,-0.545994,0.000000,0.482823
4,1.013460,0.023364,-2.136266
5,-0.685733,-0.862155,1.204126
6,-0.858191,-1.300200,0.210353


In [17]:
df.fillna({1:0.5,2:1})
# 通过传入一个字典将缺失值修改为不同填充值

,0,1,2
0,1.243484,0.500000,1.000000
1,-0.076418,0.500000,1.000000
2,0.262427,0.500000,1.862489
3,-0.545994,0.500000,0.482823
4,1.013460,0.023364,-2.136266
5,-0.685733,-0.862155,1.204126
6,-0.858191,-1.300200,0.210353


In [18]:
df = pd.DataFrame(np.random.standard_normal((6,3)))

In [19]:
df.iloc[2:,1] = np.nan
df.iloc[4:,2] = np.nan
df

,0,1,2
0,-0.267089,0.185257,2.114857
1,-0.425269,-0.633389,0.596138
2,1.767110,NaN,0.053897
3,1.213269,NaN,-1.054087
4,0.038347,NaN,NaN
5,-1.128389,NaN,NaN


In [20]:
df.ffill()
# 向前填充 forward fill
# 向后填充bfill

,0,1,2
0,-0.267089,0.185257,2.114857
1,-0.425269,-0.633389,0.596138
2,1.767110,-0.633389,0.053897
3,1.213269,-0.633389,-1.054087
4,0.038347,-0.633389,-1.054087
5,-1.128389,-0.633389,-1.054087


In [21]:
df.ffill(limit=2)

,0,1,2
0,-0.267089,0.185257,2.114857
1,-0.425269,-0.633389,0.596138
2,1.767110,-0.633389,0.053897
3,1.213269,-0.633389,-1.054087
4,0.038347,NaN,-1.054087
5,-1.128389,NaN,-1.054087


In [22]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [23]:
data.fillna(data.mean())
# 按照中位数等填充

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

删除重复值

In [24]:
data = pd.DataFrame({"K1":["one","two"]*3 + ["two"],
                     "K2":[1,1,2,3,3,4,4]})
data

,K1,K2
0,one,1
1,two,1
2,one,2
3,two,3
4,one,3
5,two,4
6,two,4


In [25]:
data.duplicated()
# 判断每一行是不是重复行。
# 它返回一个布尔型 Series：
# True：这一行和前面某一行重复
# False：这一行第一次出现，不算重复

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [26]:
data.drop_duplicates()

,K1,K2
0,one,1
1,two,1
2,one,2
3,two,3
4,one,3
5,two,4


In [27]:
data["v1"] = range(7)

In [28]:
data

,K1,K2,v1
0,one,1,0
1,two,1,1
2,one,2,2
3,two,3,3
4,one,3,4
5,two,4,5
6,two,4,6


In [29]:
data.drop_duplicates(subset=["K1"])

,K1,K2,v1
0,one,1,0
1,two,1,1


使用函数或映射转换数据

In [30]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                                                             "pastrami", "corned beef", "bacon",
                               "pastrami", "honey ham", "nova lox"],
                        "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})


In [31]:
data

,food,ounces
0,bacon,4.0
1,pulled pork,3.0
2,bacon,12.0
3,pastrami,6.0
4,corned beef,7.5
5,bacon,8.0
6,pastrami,3.0
7,honey ham,5.0
8,nova lox,6.0


In [32]:
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}

In [33]:
data['animal'] = data["food"].map(meat_to_animal)
data

,food,ounces,animal
0,bacon,4.0,pig
1,pulled pork,3.0,pig
2,bacon,12.0,pig
3,pastrami,6.0,cow
4,corned beef,7.5,cow
5,bacon,8.0,pig
6,pastrami,3.0,cow
7,honey ham,5.0,pig
8,nova lox,6.0,salmon


替换值

In [34]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [35]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [36]:
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [37]:
data.replace({-999:np.nan,-1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

重命名轴索引

In [38]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                                         index=["Ohio", "Colorado", "New York"],
                     columns=["one", "two", "three", "four"])

In [39]:
data

,one,two,three,four
Ohio,0,1,2,3
Colorado,4,5,6,7
New York,8,9,10,11


In [40]:
def transform(x):
    return x[:4].upper()

data.index.map(transform)
# 把 data 的索引逐个拿出来处理，取前 4 个字符并转成大写

Index(['OHIO', 'COLO', 'NEW '], dtype='str')

离散化与分箱

In [41]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [42]:
bins = [18,25,35,60,100]

In [43]:
age_categories = pd.cut(ages,bins)
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [44]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [45]:
age_categories.value_counts()


(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [46]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [47]:
pd.cut(ages,bins,labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, str): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [48]:
data = np.random.uniform(size=20)
data

array([0.94067318, 0.55308308, 0.34839277, 0.02840468, 0.54752904,
       0.63386554, 0.45154069, 0.82600727, 0.75791259, 0.9771017 ,
       0.2128799 , 0.81552541, 0.82227366, 0.65202329, 0.30309451,
       0.53279238, 0.13775904, 0.24516662, 0.13542963, 0.08789514])

In [49]:
pd.cut(data, 4, precision=2)
# 四等分，小数点精确到两位

[(0.74, 0.98], (0.5, 0.74], (0.27, 0.5], (0.027, 0.27], (0.5, 0.74], ..., (0.5, 0.74], (0.027, 0.27], (0.027, 0.27], (0.027, 0.27], (0.027, 0.27]]
Length: 20
Categories (4, interval[float64, right]): [(0.027, 0.27] < (0.27, 0.5] < (0.5, 0.74] < (0.74, 0.98]]

In [50]:
data =np.random.standard_normal(1000)
data

array([-1.02983384e+00,  6.75487549e-01, -9.38440178e-01,  2.59953068e+00,
       -2.88332726e-01,  1.16053220e-01,  1.44286633e+00,  3.57593389e-02,
        1.11168439e+00,  1.55782990e-01, -3.70514610e-01, -8.02345227e-01,
       -1.51283440e-01, -1.05721770e-03,  3.00949590e+00, -1.89091356e+00,
        9.22696004e-01,  7.11897260e-01, -1.70547824e-01, -2.03030429e+00,
       -3.17349433e-01,  3.12677593e-01, -8.06516135e-01,  5.48950753e-02,
        3.79473765e-01, -1.46897670e+00,  1.02010480e-01,  6.08682866e-01,
        1.10576224e+00,  6.53367242e-01, -1.13743321e+00,  1.20349795e-01,
        2.35438948e+00,  8.43101965e-01, -2.05402114e+00, -9.16748358e-01,
       -1.01272484e+00,  1.87869473e+00, -7.43592757e-01, -9.94067861e-03,
        1.23723254e+00, -6.90490428e-01,  1.59042868e+00, -6.96346434e-01,
        1.41468468e+00, -1.49898941e+00, -1.58792676e-01, -1.26106070e+00,
       -1.11569498e+00, -1.39646215e-01,  7.40242796e-01, -6.50882512e-02,
       -6.13381225e-01,  

In [51]:
quantiles = pd.qcut(data,4,precision=4)
quantiles

[(-2.9216, -0.7392], (0.6521, 3.0095], (-2.9216, -0.7392], (0.6521, 3.0095], (-0.7392, -0.07044], ..., (-0.07044, 0.6521], (-2.9216, -0.7392], (-0.07044, 0.6521], (0.6521, 3.0095], (-0.7392, -0.07044]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.9216, -0.7392] < (-0.7392, -0.07044] < (-0.07044, 0.6521] < (0.6521, 3.0095]]

In [52]:
quantiles.value_counts()
# cut：按数值区间等宽分箱
# qcut：按分位数分箱，尽量每箱数量差不多

(-2.9216, -0.7392]     250
(-0.7392, -0.07044]    250
(-0.07044, 0.6521]     250
(0.6521, 3.0095]       250
Name: count, dtype: int64

In [53]:
pd.qcut(data,[0,0.1,0.5,0.9,1.]).value_counts
# 自定义分位数（必须介于0和1）

<bound method Categorical.value_counts of [(-1.332, -0.0704], (-0.0704, 1.179], (-1.332, -0.0704], (1.179, 3.009], (-1.332, -0.0704], ..., (-0.0704, 1.179], (-1.332, -0.0704], (-0.0704, 1.179], (-0.0704, 1.179], (-1.332, -0.0704]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.9219999999999997, -1.332] < (-1.332, -0.0704] < (-0.0704, 1.179] < (1.179, 3.009]]>

检测和过滤异常值

In [54]:
data = pd.DataFrame(np.random.standard_normal((1000,4)))
display(data)

,0,1,2,3
0,-0.125264,0.281723,-1.421569,-0.958345
1,-0.777573,-1.160927,-0.133992,0.626035
2,-0.125115,0.188659,-1.137374,1.050663
3,0.937283,-1.346712,2.020071,-0.050500
4,1.358082,-0.213689,1.148799,-0.729244
...,...,...,...,...
995,0.592833,-0.530172,-0.293296,-0.466130
996,0.838622,0.119662,0.511838,0.223750
997,0.618795,1.731123,-0.273986,-0.495603
998,0.632332,2.593766,0.526098,1.872899


In [55]:
col = data[2]
col[col.abs() > 3]
# 找出指定列绝对值大于三的值

311    3.199901
Name: 2, dtype: float64

In [56]:
data[(data.abs()>3).any(axis=1)] #按行处理
# 把 data 中“任意一列的值超过 3（不管正负）”的那些行筛选出来

,0,1,2,3
175,0.569328,-0.794009,-0.026840,3.727234
185,1.088257,-3.211266,-0.165890,0.258000
199,-0.169044,3.511545,1.786111,-0.549762
311,-0.749342,0.367329,3.199901,0.345169
319,1.703117,1.107585,-0.376354,3.096749
364,1.229804,1.759018,0.951776,3.085080
473,-0.732478,-3.216200,-0.805012,0.150275
548,1.451748,-0.057335,-0.212131,3.180173
852,-0.077300,-0.229977,0.320501,3.344195


In [57]:
data[data.abs() > 3] = np.sign(data) * 3
# 把 data 中绝对值大于 3 的元素截断到 3 或 -3
# np.sign() 会返回每个数的符号：
# 正数 -> 1
# 负数 -> -1
# 0 -> 0
display(data)

,0,1,2,3
0,-0.125264,0.281723,-1.421569,-0.958345
1,-0.777573,-1.160927,-0.133992,0.626035
2,-0.125115,0.188659,-1.137374,1.050663
3,0.937283,-1.346712,2.020071,-0.050500
4,1.358082,-0.213689,1.148799,-0.729244
...,...,...,...,...
995,0.592833,-0.530172,-0.293296,-0.466130
996,0.838622,0.119662,0.511838,0.223750
997,0.618795,1.731123,-0.273986,-0.495603
998,0.632332,2.593766,0.526098,1.872899


In [58]:
data.describe()

,0,1,2,3
count,1000.000000,1000.000000,1000.000000,1000.000000
mean,0.013591,0.006903,-0.039916,0.021178
std,0.935270,0.976650,0.973705,0.998315
min,-2.992156,-3.000000,-2.839603,-2.938692
25%,-0.620593,-0.659609,-0.695331,-0.665081
50%,-0.018796,0.006074,-0.031498,0.025969
75%,0.712927,0.675249,0.578067,0.689937
max,2.805436,3.000000,3.000000,3.000000


In [59]:
np.sign(data).head(10)

,0,1,2,3
0,-1.0,1.0,-1.0,-1.0
1,-1.0,-1.0,-1.0,1.0
2,-1.0,1.0,-1.0,1.0
3,1.0,-1.0,1.0,-1.0
4,1.0,-1.0,1.0,-1.0
5,-1.0,-1.0,-1.0,1.0
6,-1.0,1.0,1.0,1.0
7,-1.0,-1.0,1.0,-1.0
8,1.0,-1.0,1.0,-1.0
9,1.0,-1.0,1.0,1.0


排列和随机抽样

In [60]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5,7)))
df

,0,1,2,3,4,5,6
0,0,1,2,3,4,5,6
1,7,8,9,10,11,12,13
2,14,15,16,17,18,19,20
3,21,22,23,24,25,26,27
4,28,29,30,31,32,33,34


In [61]:
sampler = np.random.permutation(5)
display(sampler)
# 将0 到 4 这 5 个整数随机打乱顺序

array([4, 1, 3, 0, 2])

In [62]:
df.take(sampler)
# take() 是按位置索引取值，不是按标签取值

,0,1,2,3,4,5,6
4,28,29,30,31,32,33,34
1,7,8,9,10,11,12,13
3,21,22,23,24,25,26,27
0,0,1,2,3,4,5,6
2,14,15,16,17,18,19,20


In [63]:
df.iloc[sampler]

,0,1,2,3,4,5,6
4,28,29,30,31,32,33,34
1,7,8,9,10,11,12,13
3,21,22,23,24,25,26,27
0,0,1,2,3,4,5,6
2,14,15,16,17,18,19,20


In [64]:
column_sampler = np.random.permutation(7)
column_sampler

array([6, 5, 4, 1, 2, 0, 3])

In [65]:
df.take(column_sampler,axis=1)

,6,5,4,1,2,0,3
0,6,5,4,1,2,0,3
1,13,12,11,8,9,7,10
2,20,19,18,15,16,14,17
3,27,26,25,22,23,21,24
4,34,33,32,29,30,28,31


In [66]:
df.sample(3)
# 从 df 中随机抽取 3 行

,0,1,2,3,4,5,6
2,14,15,16,17,18,19,20
0,0,1,2,3,4,5,6
4,28,29,30,31,32,33,34


In [67]:
choice = pd.Series([5,7,-1,6,4])
choice.sample(n=10,replace=True)
# 从 choice 这 5 个数里随机抽 10 次，并且允许重复抽到同一个值

2   -1
4    4
1    7
0    5
2   -1
3    6
1    7
2   -1
4    4
0    5
dtype: int64

计算指示/虚拟变量

In [68]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                    "data1": range(6)})

In [69]:
df

,key,data1
0,b,0
1,b,1
2,a,2
3,c,3
4,a,4
5,b,5


In [70]:
pd.get_dummies(df["key"],dtype=float)
# 把 df["key"] 这一列的分类值转换成哑变量矩阵
# 把文字类别变成计算机更容易处理的数字形式

,a,b,c
0,0.0,1.0,0.0
1,0.0,1.0,0.0
2,1.0,0.0,0.0
3,0.0,0.0,1.0
4,1.0,0.0,0.0
5,0.0,1.0,0.0


In [71]:
dummies = pd.get_dummies(df["key"],prefix="key",dtype=float)
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy
# 先把 key 列做成哑变量，再把这些哑变量列拼接到 data1 那一列旁边
# 通过prefix="key",列名变成key_a key_b key_c
# df[['data1]]取出原表的data1，使用双中括号，结果还是DataFrame而不是Series
# 通过join()横向拼接

,data1,key_a,key_b,key_c
0,0,0.0,1.0,0.0
1,1,0.0,1.0,0.0
2,2,1.0,0.0,0.0
3,3,0.0,0.0,1.0
4,4,1.0,0.0,0.0
5,5,0.0,1.0,0.0


In [72]:
mnames = ['movie_id','title','genres']
movies = pd.read_table("datasets/movielens/movies.dat",sep="::",header=None,names=mnames,engine="python")
movies[:10]

,movie_id,title,genres
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children's
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller


In [73]:
dummies = movies["genres"].str.get_dummies("|")
dummies.iloc[:10,:6]

,Action,Adventure,Animation,Children's,Comedy,Crime
0,0,0,1,1,1,0
1,0,1,0,1,0,0
2,0,0,0,0,1,0
3,0,0,0,0,1,0
4,0,0,0,0,1,0
5,1,0,0,0,0,1
6,0,0,0,0,1,0
7,0,1,0,1,0,0
8,1,0,0,0,0,0
9,1,1,0,0,0,0


In [74]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))
movies_windic.iloc[0]
#将dummies的列名加到Genre后，然后拼接到movies表，在查看第一行数据

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

In [75]:
np.random.seed(12345)
values = np.random.uniform(size=10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [76]:
bins = [0,0.2,0.4,0.6,0.8,1]
pd.get_dummies(pd.cut(values,bins))
# pd.get_dummies 讲区间标签转成哑变量

,"(0.0, 0.2]","(0.2, 0.4]","(0.4, 0.6]","(0.6, 0.8]","(0.8, 1.0]"
0,False,False,False,False,True
1,False,True,False,False,False
2,True,False,False,False,False
3,False,True,False,False,False
4,False,False,True,False,False
5,False,False,True,False,False
6,False,False,False,False,True
7,False,False,False,True,False
8,False,False,False,True,False
9,False,False,False,True,False


扩展数据类型

In [77]:
s = pd.Series([1,2,3,None])
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [78]:
s.dtype
# NaN 属于浮点体系
# type(s)看对象类型，s.dtype看数据类型

dtype('float64')

In [79]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())

In [80]:
s


0       1
1       2
2       3
3    <NA>
dtype: Int64

In [81]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [82]:
s = pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())

In [83]:
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [84]:
df = pd.DataFrame({"A": [1, 2, None, 4],
                    "B": ["one", "two", "three", None],
                    "C": [False, None, False, True]})


In [85]:
df

,A,B,C
0,1.0,one,False
1,2.0,two,None
2,NaN,three,False
3,4.0,NaN,True


In [86]:
type(df)

pandas.DataFrame

In [87]:
df.dtypes

A    float64
B        str
C     object
dtype: object

字符串操作

In [88]:
val = 'a,b,  guido'
val.split(",")

['a', 'b', '  guido']

In [89]:
pieces = [x.strip() for x in val.split(',')]
pieces
# split与strip结合删除空白字符

['a', 'b', 'guido']

In [ ]:
first, second,  third = pieces
# 序列解包
first + "::"  + second + "::" + third

'a::b::guido'

In [ ]:
"::".join(pieces)
# 等价于

'a::b::guido'

In [ ]:
"guido" in pieces
# 使用in关键词检测子字符串

True

In [ ]:
display(val)
val.replace(",","::")
# 将,替换为：：

'a,b,  guido'

'a::b::  guido'

正则表达式

In [94]:
import re

In [96]:
text = "foo.   bar\t.   baz.   \tqux"
text

'foo.   bar\t.   baz.   \tqux'

In [97]:
re.split(r"\s+",text)

['foo.', 'bar', '.', 'baz.', 'qux']

In [99]:
regex = re.compile(r"\s+")
regex.split(text)
# 先编译一个“匹配一个或多个空白字符”的正则表达式，再用它去切分字符串 text

['foo.', 'bar', '.', 'baz.', 'qux']

In [100]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"


In [ ]:
regex = re.compile(pattern,flags=re.IGNORECASE)
regex.findall(text)
# flags= 匹配是额外采用的规则

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [102]:
m = regex.search(text)
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [104]:
print(regex.sub("REDACTED",text))
# 将匹配值替换为指定值

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED


In [106]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
regex = re.compile(pattern,flags = re.IGNORECASE)

In [108]:
m = regex.match("wesm@bright.net")
m


<re.Match object; span=(0, 15), match='wesm@bright.net'>

In [ ]:
m.groups()
# match()从字符串开头开始匹配，group()则从匹配结果中取出匹配内容

('wesm', 'bright', 'net')

In [110]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [ ]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))
# 通过\1,\2访问匹配的分组

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com


In [124]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
         "Rob": "rob@gmail.com", "Wes": np.nan}


In [125]:
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: str

In [126]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes      False
dtype: bool

In [127]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
data.str.findall(pattern,flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [128]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [129]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [130]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: str

分类数据

In [132]:
values = pd.Series(['apple', 'orange', 'apple',
                     'apple'] * 2)
values


0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: str

In [133]:
pd.unique(values)

<StringArray>
['apple', 'orange']
Length: 2, dtype: str

In [137]:
values.value_counts()

apple     6
orange    2
Name: count, dtype: int64

In [138]:
dim = pd.Series(['apple','orange'])
dim

0     apple
1    orange
dtype: str

In [141]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2
N = len(fruits)
rng = np.random.default_rng(seed=12345)


In [142]:
df = pd.DataFrame({'fruit': fruits,
                    'basket_id': np.arange(N),
                     'count': rng.integers(3, 15, size=N),
                    'weight': rng.uniform(0, 4, size=N)},
                   columns=['basket_id', 'fruit', 'count', 'weight'])


In [143]:
df

,basket_id,fruit,count,weight
0,0,apple,11,1.564438
1,1,orange,5,1.331256
2,2,apple,12,2.393235
3,3,apple,6,0.746937
4,4,apple,5,2.691024
5,5,orange,12,3.767211
6,6,apple,10,0.992983
7,7,apple,11,3.795525


In [ ]:
fruit_cat = df['fruit'].astype("category")
# 把 df['fruit'] 这一列从普通字符串列，转换成“分类类型”列
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, str): ['apple', 'orange']

In [146]:
c = fruit_cat.array
c

['apple', 'orange', 'apple', 'apple', 'apple', 'orange', 'apple', 'apple']
Categories (2, str): ['apple', 'orange']

In [147]:
dict(enumerate(c.categories))


{0: 'apple', 1: 'orange'}

In [148]:
df

,basket_id,fruit,count,weight
0,0,apple,11,1.564438
1,1,orange,5,1.331256
2,2,apple,12,2.393235
3,3,apple,6,0.746937
4,4,apple,5,2.691024
5,5,orange,12,3.767211
6,6,apple,10,0.992983
7,7,apple,11,3.795525


In [ ]:
df['fruit'] = df['fruit'].astype('category')
# 通过赋值的方法将DataFrame列转化为分类数据

In [150]:
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, str): ['apple', 'orange']

In [151]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])
# 直接创建


In [152]:
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, str): ['bar', 'baz', 'foo']

In [ ]:
categories = ['foo', 'bar', 'baz']
codes = [0,1,2,0,0,1]
my_cats_2 = pd.Categorical.from_codes(codes,categories)
my_cats_2
# 根据编码直接构造

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, str): ['foo', 'bar', 'baz']

对分类数据的计算

In [154]:
rng = np.random.default_rng(seed=12345)
# random number generator
draws = rng.standard_normal(1000)
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [155]:
bins = pd.qcut(draws,4)

In [156]:
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [157]:
bins = pd.qcut(draws,4,labels=['Q1','Q2','Q3','Q4'])
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, str): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [159]:
bins.codes[:10]
# 前十个值落在哪号箱

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [ ]:
bins =pd.Series(bins,name='quartitle')
results = (pd.Series(draws).groupby(bins).agg(['count','min','max']).reset_index())
# 按分箱区间对 draws 分组，统计每个区间的数量、最小值和最大值
results

,quartitle,count,min,max
0,Q1,250,-3.119609,-0.678494
1,Q2,250,-0.673305,0.008009
2,Q3,250,0.018753,0.686183
3,Q4,250,0.688282,3.211418


In [162]:
results['quartitle']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartitle, dtype: category
Categories (4, str): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [164]:
categories = pd.Series(['foo','bar','baz','qux']*2).astype('category')
categories

0    foo
1    bar
2    baz
3    qux
4    foo
5    bar
6    baz
7    qux
dtype: category
Categories (4, str): ['bar', 'baz', 'foo', 'qux']

In [ ]:
categories.memory_usage(deep=True)


380

In [166]:
pd.Series(['foo','bar','baz','qux']*2).memory_usage(deep=True)

612

In [167]:
%time _ = categories = pd.Series(['foo','bar','baz','qux']*2).astype('category')
categories

CPU times: user 682 μs, sys: 73 μs, total: 755 μs
Wall time: 855 μs


0    foo
1    bar
2    baz
3    qux
4    foo
5    bar
6    baz
7    qux
dtype: category
Categories (4, str): ['bar', 'baz', 'foo', 'qux']

In [168]:
s = pd.Series(['a','b','c','d']*2)
s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: str

In [169]:
cat_s =s.astype('category')

In [170]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, str): ['a', 'b', 'c', 'd']

In [171]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [ ]:
actual_categories = ['a','b','c','d','e']
cat_s2 = cat_s.cat.set_categories(actual_categories)
cat_s2
# 通过.cat.set_categories更改数据实际类别

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, str): ['a', 'b', 'c', 'd', 'e']

In [175]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [176]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [ ]:
cat_s3 = cat_s[cat_s.isin(['a','b'])]
# 从cat_s中筛出类别为a,b的行，此时出现多余分类
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, str): ['a', 'b', 'c', 'd']

In [ ]:
cat_s3.cat.remove_unused_categories()
# 通过该方法删除未观察到的分类

0    a
1    b
4    a
5    b
dtype: category
Categories (2, str): ['a', 'b']